baseURL = 'https://note.xicuodev.top/'
languageCode = 'zh-cn'
title = '系错的技术笔记'
defaultContentLanguage = 'zh-cn'

disableKinds = []

[module]
  [module.imports]
    path = 'github.com/imfing/hextra'

[menus]
  [[menus.main]]
    name = '通用'
    pageRef = '/general/'
    weight = 10

  [[menus.main]]
    name = 'Linux'
    pageRef = '/linux/'
    weight = 15

  [[menus.main]]
    name = 'Java'
    pageRef = '/java/'
    weight = 20

  [[menus.main]]
    name = 'Android'
    pageRef = '/android/'
    weight = 25

  [[menus.main]]
    name = '.NET'
    pageRef = '/dotnet/'
    weight = 30
   
  [[menus.main]]
    name = '搜索'
    weight = 9_999
    [menus.main.params]
      type = 'search'

[params]
  shortName = '系错的技术笔记'
  description = '复习自用，公开查阅，望共同进步。'
  keywords = '笔记, 技术栈, Java'
  externalLinkDecoration = true
  [params.author]
    name = '系错'
    email = 'xicuod@outlook.com'
  [params.socialLinks]
    github = 'https://github.com/Dobefu/hugo-theme-plume'
    # Enable social links by uncommenting any of the following lines.
    # bluesky = 'https://bsky.app/profile/<your-bluesky-username>'
    # discord = 'https://discord.gg/<your-discord-server-invite-link>'
    # facebook = 'https://www.facebook.com/<your-facebook-username>'
    # github = 'https://github.com/<your-github-username>/<your-repository-name>'
    # instagram = 'https://www.instagram.com/<your-instagram-username>'
    # linkedin = 'https://www.linkedin.com/company/<your-linkedin-company-name>'
    # pinterest = 'https://www.pinterest.com/<your-pinterest-username>'
    # reddit = 'https://www.reddit.com/r/<your-reddit-subreddit-name>'
    # telegram = 'https://t.me/<your-telegram-username>'
    # tiktok = 'https://www.tiktok.com/@<your-tiktok-username>'
    # twitter = 'https://twitter.com/<your-twitter-username>'
    # whatsapp = 'https://wa.me/<your-whatsapp-number>'
    # youtube = 'https://www.youtube.com/@<your-youtube-username>'
  [params.theme]
   default = 'system'
   displayToggle = true
  [params.navbar]
    displayTitle = true
    displayLogo = true
    [params.navbar.logo]
      path = 'img/logo.png'
      dark = 'img/logo.png'
      link = '/'
      width = 40
      height = 20
  [params.comments]
    enable = true
    type = 'giscus'
    [params.comments.giscus]
      repo = 'xicuod/xicuod.github.io'
      repoId = 'R_kgDORYWR9A'
      category = 'General'
      categoryId = 'DIC_kwDORYWR9M4C3LS4'
      mapping = 'pathname'
      strict = '1'
      reactionsEnabled = '1'
      emitMetadata = '0'
      inputPosition = 'top'
      theme = 'preferred_color_scheme'
      lang = 'zh-CN'
      crossorigin = 'anonymous'
    [params.imageZoom]
      enable = true
    [params.blog.list]
      displayTags = true
    [params.toc]
      displayTags = true

[permalinks]
  [permalinks.page]
    java = '/:slug/'
    android = '/:slug/'
    dotnet = '/:slug/'
    general = '/:slug/'
    linux = '/:slug/'

[markup.highlight]
  noClasses = true
  style = 'dracula'

[markup.goldmark.extensions.passthrough]
enable = true
  [markup.goldmark.extensions.passthrough.delimiters]
  block = [ [ '\\[', '\\]' ], [ '$$', '$$' ] ]
  inline = [ [ '\\(', '\\)' ], [ '$', '$' ] ]

[outputs]
  home = ['html', 'rss']
